image: golang:1

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

stages:
  - check

go-check:
  stage: check
  script:
    - go version
    - go vet ./...
    - go test ./...
    - go build ./...